print("what is your monthly expenses on food?")
input("9500")
print("what is your monthly expenses on transport?")
input("8500")
print("what is your monthly expenses on clothe?")
input("7500")
print("what is your monthly expenses on business?")
input("6500")
print("what is your monthly expenses on shelter?")
input("5500")
print("1+2+3+4+5")
